[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SummaryPath,

    [Parameter(Mandatory = $true)]
    [string]$Repository,

    [Parameter(Mandatory = $true)]
    [int]$PullRequestNumber,

    [Parameter(Mandatory = $true)]
    [string]$WorkflowRunUrl,

    [Parameter(Mandatory = $true)]
    [string]$CommentIndexOutputPath,

    [int]$InterCommentDelaySeconds = 3,

    [int]$SecondaryRateLimitDelaySeconds = 60,

    [int]$MaxContentCreationAttempts = 5
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-GhApiJson {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [AllowNull()]
        [string]$InputJson
    )

    $tempInputPath = $null

    try {
        if ($PSBoundParameters.ContainsKey('InputJson')) {
            $tempInputPath = [System.IO.Path]::GetTempFileName()
            [System.IO.File]::WriteAllText($tempInputPath, $InputJson, [System.Text.UTF8Encoding]::new($false))
            $output = & gh @Arguments --input $tempInputPath 2>&1
        }
        else {
            $output = & gh @Arguments 2>&1
        }

        if ($LASTEXITCODE -ne 0) {
            throw ('gh {0} failed: {1}' -f ($Arguments -join ' '), (($output | ForEach-Object { [string]$_ }) -join [Environment]::NewLine))
        }

        return (($output | ForEach-Object { [string]$_ }) -join [Environment]::NewLine | ConvertFrom-Json)
    }
    finally {
        if ($tempInputPath -and (Test-Path $tempInputPath)) {
            Remove-Item -Path $tempInputPath -Force -ErrorAction SilentlyContinue
        }
    }
}

function Write-JsonFile {
    param([string]$Path, [object]$InputObject)
    $directory = Split-Path -Parent $Path
    if ($directory) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    $json = $InputObject | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllText($Path, $json + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

function Get-IssueComments {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Repository,

        [Parameter(Mandatory = $true)]
        [int]$PullRequestNumber
    )

    $page = 1
    $comments = @()

    while ($true) {
        $pageComments = @(Invoke-GhApiJson -Arguments @('api', "repos/$Repository/issues/$PullRequestNumber/comments?per_page=100&page=$page"))
        if ($pageComments.Count -eq 0) {
            break
        }

        $comments += $pageComments
        if ($pageComments.Count -lt 100) {
            break
        }

        $page++
    }

    return $comments
}

function New-CommentMarker {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter(Mandatory = $true)]
        [string]$Version
    )

    return '<!-- inspectra-non-success-detail:{0}/{1} -->' -f $PackageId.ToLowerInvariant(), $Version.ToLowerInvariant()
}

function New-CommentBody {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Marker,

        [Parameter(Mandatory = $true)]
        [object]$Item,

        [Parameter(Mandatory = $true)]
        [string]$WorkflowRunUrl
    )

    $mdTick = [string][char]96
    $lines = @(
        $Marker,
        ('Non-success detail for {0}{1} {2}{0}' -f $mdTick, $Item.packageId, $Item.version),
        '',
        ('- Status: {0}{1}{0}' -f $mdTick, $Item.status),
        ('- Disposition: {0}{1}{0}' -f $mdTick, $Item.disposition),
        ('- Phase: {0}{1}{0}' -f $mdTick, $Item.phase),
        ('- Classification: {0}{1}{0}' -f $mdTick, $Item.classification),
        ('- Source workflow run: {0}{1}{0}' -f $mdTick, $WorkflowRunUrl),
        '',
        'Reason:',
        '~~~text',
        [string]$Item.reason,
        '~~~',
        '',
        'Generated by `Promote Untrusted Analysis Results`.'
    )

    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function Test-IsSecondaryRateLimitError {
    param([string]$Message)

    return $Message -match 'secondary rate limit' -or
        $Message -match 'temporarily blocked from content creation' -or
        $Message -match 'HTTP 403'
}

function Upsert-Comment {
    param(
        [Parameter(Mandatory = $true)]
        [object]$ExistingComment,

        [Parameter(Mandatory = $true)]
        [string]$Repository,

        [Parameter(Mandatory = $true)]
        [int]$PullRequestNumber,

        [Parameter(Mandatory = $true)]
        [string]$Body,

        [Parameter(Mandatory = $true)]
        [int]$MaxAttempts,

        [Parameter(Mandatory = $true)]
        [int]$SecondaryRateLimitDelaySeconds
    )

    $payload = [ordered]@{ body = $Body } | ConvertTo-Json -Depth 5 -Compress

    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        try {
            if ($ExistingComment) {
                return Invoke-GhApiJson -Arguments @('api', "repos/$Repository/issues/comments/$($ExistingComment.id)", '--method', 'PATCH') -InputJson $payload
            }

            return Invoke-GhApiJson -Arguments @('api', "repos/$Repository/issues/$PullRequestNumber/comments", '--method', 'POST') -InputJson $payload
        }
        catch {
            $message = $_.Exception.Message
            if ($attempt -eq $MaxAttempts -or -not (Test-IsSecondaryRateLimitError -Message $message)) {
                throw
            }

            Start-Sleep -Seconds ($SecondaryRateLimitDelaySeconds * $attempt)
        }
    }

    throw 'Unreachable comment upsert failure.'
}

$summary = Get-Content $SummaryPath -Raw | ConvertFrom-Json
$existingComments = @(Get-IssueComments -Repository $Repository -PullRequestNumber $PullRequestNumber)
$commentIndex = @()
$itemCount = @($summary.nonSuccessItems).Count
$itemIndex = 0

foreach ($item in @($summary.nonSuccessItems)) {
    $itemIndex++
    $marker = New-CommentMarker -PackageId $item.packageId -Version $item.version
    $body = New-CommentBody -Marker $marker -Item $item -WorkflowRunUrl $WorkflowRunUrl
    $existingComment = $existingComments | Where-Object { $_.body -like "*$marker*" } | Select-Object -First 1

    $comment = Upsert-Comment `
        -ExistingComment $existingComment `
        -Repository $Repository `
        -PullRequestNumber $PullRequestNumber `
        -Body $body `
        -MaxAttempts $MaxContentCreationAttempts `
        -SecondaryRateLimitDelaySeconds $SecondaryRateLimitDelaySeconds

    $commentIndex += [ordered]@{
        packageId = $item.packageId
        version = $item.version
        commentUrl = $comment.html_url
    }

    if ($itemIndex -lt $itemCount -and $InterCommentDelaySeconds -gt 0) {
        Start-Sleep -Seconds $InterCommentDelaySeconds
    }
}

Write-JsonFile -Path $CommentIndexOutputPath -InputObject $commentIndex
