[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SummaryPath,

    [Parameter(Mandatory = $true)]
    [string]$WorkflowRunUrl,

    [Parameter(Mandatory = $true)]
    [string]$BodyOutputPath,

    [string]$CommentIndexPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-MarkdownLink {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Label,

        [AllowNull()]
        [string]$Url
    )

    if ([string]::IsNullOrWhiteSpace($Url)) {
        return $Label
    }

    return "[{0}]({1})" -f $Label, $Url
}

$mdTick = [string][char]96
$summary = Get-Content $SummaryPath -Raw | ConvertFrom-Json
$commentIndex = @{}

if (-not [string]::IsNullOrWhiteSpace($CommentIndexPath) -and (Test-Path $CommentIndexPath)) {
    foreach ($entry in @(Get-Content $CommentIndexPath -Raw | ConvertFrom-Json)) {
        $commentUrl = if ($entry.PSObject.Properties.Name -contains 'commentUrl') {
            [string]$entry.commentUrl
        }
        else {
            $null
        }

        if (-not [string]::IsNullOrWhiteSpace($commentUrl)) {
            $commentIndex["$($entry.packageId.ToLowerInvariant())|$($entry.version.ToLowerInvariant())"] = $commentUrl
        }
    }
}

$nonSuccessItems = @($summary.nonSuccessItems)
$bodyLines = @(
    ('Promote the completed untrusted analysis batch {0}{1}{0}.' -f $mdTick, $summary.batchId),
    '',
    'Source workflow run:',
    ('- {0}{1}{0}' -f $mdTick, $WorkflowRunUrl),
    '',
    'Result summary:',
    ('- Success: {0}{1}{0}' -f $mdTick, $summary.successCount),
    ('- Terminal negative: {0}{1}{0}' -f $mdTick, $summary.terminalNegativeCount),
    ('- Retryable failure: {0}{1}{0}' -f $mdTick, $summary.retryableFailureCount),
    ('- Terminal failure: {0}{1}{0}' -f $mdTick, $summary.terminalFailureCount),
    ('- Missing artifacts: {0}{1}{0}' -f $mdTick, $summary.missingCount),
    '',
    'Non-success details:'
)

if ($nonSuccessItems.Count -eq 0) {
    $bodyLines += '- None.'
}
else {
    foreach ($item in $nonSuccessItems) {
        $commentUrl = $commentIndex["$($item.packageId.ToLowerInvariant())|$($item.version.ToLowerInvariant())"]
        $label = '{0} {1}' -f $item.packageId, $item.version
        $bodyLines += ('- {0}: {1}, {2}' -f (Get-MarkdownLink -Label $label -Url $commentUrl), $item.status, $item.classification)
    }
}

$bodyLines += ''
$bodyLines += 'Generated by `Promote Untrusted Analysis Results`.'
[System.IO.File]::WriteAllText($BodyOutputPath, ($bodyLines -join [Environment]::NewLine) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
